// Book catalog — original titles, authors, and content
window.BOOKS = [
  {
    id: "small-rains",
    title: "The Small Rains",
    author: "Ines Voss",
    year: 2024,
    type: "ebook",
    genre: "Literary Fiction",
    pages: 284,
    minutes: 412,
    rating: 4.6,
    ratings: 2841,
    price: "$14.99",
    cover: { bg: "oklch(0.72 0.17 35)", fg: "oklch(0.98 0.02 85)", style: "type" },
    blurb: "A cartographer returns to the coastal town she mapped as a child, only to find the shoreline — and her memory of it — has quietly moved.",
    excerpt: "The tide came in the way it always had, which is to say, not the way anyone remembered. Mira set her instruments down on the rocks and watched the water find its old marks, then lose them. She had drawn this coast when she was twelve. The map was wrong now. Everything she had been certain of was wrong now, and the gulls did not care.\n\nShe thought about her mother, who had been certain of almost nothing and had seemed, for that reason, to live inside a much larger house than the rest of them. There had been a kind of weather inside her. Mira had spent most of her adult life drafting careful lines against that weather. Here, on the rocks, she understood for the first time that the lines had never held. They had only looked like they held, from far away, on paper.\n\nThe boat from the mainland came in at four. She could hear it before she could see it — a low, patient engine, the kind of sound that belonged to the harbor more than to any particular vessel. She packed up. She walked the long way back, past the church with the leaning spire and the house where she had been a child, and she did not stop at either."
  },
  {
    id: "copper-wire",
    title: "Copper Wire",
    author: "Theo Alonzo",
    year: 2023,
    type: "audiobook",
    genre: "Memoir",
    pages: 312,
    minutes: 548,
    rating: 4.8,
    ratings: 5102,
    price: "$18.99",
    cover: { bg: "oklch(0.82 0.14 85)", fg: "oklch(0.25 0.04 50)", style: "stripe" },
    blurb: "An electrician's son traces three generations of his family through the houses they wired, the radios they repaired, and the signals they could never quite receive.",
    excerpt: "My father could listen to a house. He'd stand in the kitchen with his palm flat on the wall and close his eyes and tell you, without opening the panel, which circuit was loaded and which was starving. I don't know if this was a real skill or a kind of theater he performed for the customer. Probably both."
  },
  {
    id: "field-manual",
    title: "A Field Manual for Quiet People",
    author: "Pilar Okafor",
    year: 2025,
    type: "ebook",
    genre: "Essays",
    pages: 196,
    minutes: 288,
    rating: 4.4,
    ratings: 1203,
    price: "$12.99",
    cover: { bg: "oklch(0.72 0.1 150)", fg: "oklch(0.2 0.02 60)", style: "grid" },
    blurb: "Thirty short essays on attention, shyness, and the small, specific pleasures of being overlooked.",
    excerpt: "There is a particular freedom in being the second-most-interesting person in any room. No one asks you the hard questions. No one remembers what you said last time. You can change your mind about almost anything and nobody will bring it up at dinner."
  },
  {
    id: "last-ferry",
    title: "The Last Ferry to Ostersund",
    author: "Margit Halvorsen",
    year: 2022,
    type: "ebook",
    genre: "Mystery",
    pages: 368,
    minutes: 532,
    rating: 4.5,
    ratings: 8421,
    price: "$11.99",
    cover: { bg: "oklch(0.5 0.12 240)", fg: "oklch(0.95 0.02 240)", style: "diag" },
    blurb: "A retired harbor inspector is called back to duty for one last crossing — and finds a passenger who shouldn't be aboard.",
    excerpt: "The manifest listed forty-two passengers. Inspector Vinje counted forty-three heads on the upper deck, and then, because he did not trust himself in cold weather, counted them again."
  },
  {
    id: "orchard-debt",
    title: "Orchard Debt",
    author: "Junia Park",
    year: 2024,
    type: "audiobook",
    genre: "Literary Fiction",
    pages: 244,
    minutes: 436,
    rating: 4.3,
    ratings: 612,
    price: "$15.99",
    cover: { bg: "oklch(0.7 0.12 280)", fg: "oklch(0.98 0.02 85)", style: "circle" },
    blurb: "Two sisters inherit their grandfather's pear orchard, along with every unpaid favor it took to keep it.",
    excerpt: "The trees had been planted by a man who believed in the long view, which is another way of saying he left most of the picking to other people."
  },
  {
    id: "signal-fire",
    title: "Signal Fire",
    author: "Ademar Costa",
    year: 2025,
    type: "article",
    genre: "Longform",
    pages: 42,
    minutes: 58,
    rating: 4.7,
    ratings: 318,
    price: "Free",
    cover: { bg: "oklch(0.25 0.04 50)", fg: "oklch(0.82 0.14 85)", style: "type" },
    blurb: "How a volunteer fire lookout in the Serra do Mar spent nine summers watching for smoke and one winter writing about it.",
    excerpt: "For most of the season there was nothing. Nothing is the product, he told me, the first time I climbed up. You are paid to produce nothing, and to produce it continuously."
  },
  {
    id: "blue-hour",
    title: "The Blue Hour Almanac",
    author: "Séverine Dubois",
    year: 2023,
    type: "ebook",
    genre: "Nature Writing",
    pages: 220,
    minutes: 324,
    rating: 4.9,
    ratings: 4210,
    price: "$16.99",
    cover: { bg: "oklch(0.6 0.14 220)", fg: "oklch(0.95 0.04 90)", style: "stripe" },
    blurb: "A year of dusks, catalogued from a single window in the Jura.",
    excerpt: "The blue hour is not really an hour. On a clear evening in June it lasts perhaps eleven minutes. In November it can take the whole afternoon."
  },
  {
    id: "quiet-engine",
    title: "Quiet Engine",
    author: "Wendell Ibekwe",
    year: 2024,
    type: "audiobook",
    genre: "Technology",
    pages: 298,
    minutes: 496,
    rating: 4.2,
    ratings: 1842,
    price: "$17.99",
    cover: { bg: "oklch(0.45 0.08 25)", fg: "oklch(0.9 0.08 85)", style: "grid" },
    blurb: "A plainspoken tour of the infrastructure we stopped noticing — cell towers, substations, and the people who keep them running.",
    excerpt: "Every city has a second city underneath it, and a third city on top of it, and most of us spend our lives in the first one."
  },
  {
    id: "paper-birds",
    title: "Paper Birds",
    author: "Livia Marchetti",
    year: 2021,
    type: "ebook",
    genre: "Short Stories",
    pages: 176,
    minutes: 248,
    rating: 4.4,
    ratings: 982,
    price: "$13.99",
    cover: { bg: "oklch(0.88 0.08 70)", fg: "oklch(0.3 0.08 25)", style: "diag" },
    blurb: "Eleven stories about small, stubborn people doing small, stubborn things in the northern suburbs of Milan.",
    excerpt: "Signora Conti had been folding the same newspaper for forty years, and in that time she had read perhaps twelve of the articles."
  },
  {
    id: "north-catalog",
    title: "The North Catalog",
    author: "Halldór Jonsson",
    year: 2022,
    type: "ebook",
    genre: "Travel",
    pages: 340,
    minutes: 472,
    rating: 4.6,
    ratings: 2210,
    price: "$19.99",
    cover: { bg: "oklch(0.35 0.06 220)", fg: "oklch(0.95 0.02 85)", style: "type" },
    blurb: "Every road above the sixtieth parallel, walked, driven, or argued about.",
    excerpt: "You can drive for six hours in the Westfjords and see one other car, and it will be the same car, and the person inside will wave at you three times."
  }
];

window.SHELVES = [
  { id: "reading", name: "Reading now", ids: ["small-rains", "copper-wire"] },
  { id: "queue", name: "Up next", ids: ["field-manual", "last-ferry", "orchard-debt"] },
  { id: "finished", name: "Finished", ids: ["blue-hour", "paper-birds"] }
];

window.DISCOVER_SHELVES = [
  { id: "staff", name: "Staff picks this week", kicker: "Hand-picked", ids: ["small-rains", "blue-hour", "signal-fire", "copper-wire"] },
  { id: "new", name: "New arrivals", kicker: "Fresh off the press", ids: ["field-manual", "orchard-debt", "quiet-engine", "signal-fire"] },
  { id: "quiet", name: "Quiet reads for a long afternoon", kicker: "Curated", ids: ["field-manual", "paper-birds", "blue-hour", "small-rains"] },
  { id: "north", name: "Going north", kicker: "Travelogue", ids: ["north-catalog", "last-ferry", "blue-hour", "copper-wire"] }
];
